### ISSUE TITLE
Porosity missing in component mass conservation?

### ISSUE THREAD

**Issue by timokoch** [Simulation-Benchmarks/11thSPE-CSP#12]
The current formulation (2.2) reads
```math
\sum_{\alpha=w, n}\left[\frac{\partial\left(\rho_\alpha \phi s_\alpha \chi_\alpha^i J\right)}{\partial t}+\boldsymbol{\nabla} \cdot\left(\rho_\alpha \boldsymbol{u}_\alpha m_\alpha^i+\rho_\alpha j_\alpha^i\right)\right]=0
```
with (2.3)
```math
\boldsymbol{j}_\alpha^i=-\left(s_\alpha D_\alpha+E\left|\boldsymbol{u}_\alpha\right|\right) \nabla \chi_\alpha^i
```

(1) I think it should be 
```math
\boldsymbol{j}_\alpha^i=-\left(\phi s_\alpha D_\alpha+E\left|\boldsymbol{u}_\alpha\right|\right) \nabla \chi_\alpha^i
```
Since porosity is a space-dependent field with discontinuities at material boundaries, its effect cannot be included in the constant diffusion coefficients. Without porosity, I think we are not computing the expected fluxes of the conserved quantity $\rho_\alpha \phi s_\alpha \chi_\alpha^i$ over material discontinuities. (It would correspond to some assumptions of jumping diffusion coefficients.) For the advective parts, this contribution is included in the velocity.

(2) the formula contains $m_\alpha^i$ in the advective term. Is this a typo (I couldn't find the definition of $m$)? Maybe should be $\chi_\alpha^i$ instead?

**Comment by berndflemisch** [comment]
Let's ping @JMNordbotten here to get the discussion going.

**Comment by JMNordbotten** [comment]
We had this discussion in the pre-launch phase, and concluded that since $D_\alpha$ depends on facies, it is redundant to also multiply with facies-dependent porosity. 

With that same justification, I am still inclined to keep (2.3) as written. 

The question can then be transferred to Table 2.1 and 3.1 and rephrased as follows: Is it reasonable to provide the same diffusion coefficient for facies 1-6, or should the change in material properties (porosity, permeability, etc.) also be reflected in a change in the diffusion coefficients? If yes, what would be a reasonable model for the diffusion coefficient? Certainly it should be zero if the permeability is zero, and similarly if the porosity is zero (as already stated for Facies 7). 

I do not feel particularly strongly about the diffusion coefficients in Table 3.1., and would not mind if they depend (or are proportional) to porosity. This will have essentially no impact on 11A (since the porosity is essentially constant), but may have a minor impact on 11B and 11C.

**Comment by berndflemisch** [comment]
Has been fixed in the description.
